version: '2'

services:
  proxy:
    build: nginx/
    ports:
    - 7080:7080
    networks:
    - net
    depends_on:
    - app
    hostname: proxy
    container_name: proxy

  app:
    build: tomcat/
    ports:
    - 8080
    networks:
    - net
    hostname: app

networks:
  net:
    driver: bridge