proxy:
  build: nginx/
  ports:
   - "7080:7080"
  links:
   - app01
   - app02
  hostname: "proxy"

app01:
  build: tomcat/
  expose:
   - "8080"
  ports:
   - "8180:8080"
  hostname: "app01"

app02:
  build: tomcat/
  expose:
   - "8080"
  ports:
   - "8280:8080"
  hostname: "app01"

mongodata:
  image: mongo:latest
  volumes:
    - /data/db
  command: --break-mongo

mongo:
  image: mongo:latest
  volumes_from:
    - mongodata
  ports:
    - "27017:27017"
  command: --smallfiles --rest --auth